import { Inter } from "next/font/google";
import "./styles/globals.css";
import AuthButton from "./components/AuthButton";
import SessionProvider from "@/app/components/SessionProvider";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Teehee",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {" "}
          {/*Add session={session} */}
          <nav className="sidebar">
            <h1>Title</h1>
            <p>Links</p>
            <AuthButton />
          </nav>
          <main className="maincontent">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
