import { Inter } from "next/font/google";
import "./styles/globals.css";
import AuthButton from "./components/AuthButton";
import SessionProvider from "@/app/components/SessionProvider";
import { getServerSession } from "next-auth";
import Link from "next/link";
import clientPromise from "./lib/mongodb";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Teehee",
  description: "Generated by create next app",
};

export const session = await getServerSession();
const mongoClient = await clientPromise;
if (session) {
  const { email } = session?.user;
}
export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <nav className="sidebar">
            <h1>Title</h1>
            <Link href="/todos">Todos</Link>
            <AuthButton />
          </nav>
          <main className="maincontent">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
