import { Inter } from "next/font/google";
import "./styles/globals.css";
import AuthButton from "./components/AuthButton";
import SessionProvider from "@/app/components/SessionProvider";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Teehee",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <nav className="sidebar">
            <Link href="/" className="title">
              Productivity Tracker
            </Link>
            {/* {session ? <UserData /> : null} */}
            <Navbar />
            <AuthButton />
          </nav>
          <main className="maincontent">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
